package org.fenixedu.academic.domain.person.personIdentifier;

import java.util.Optional;
import java.util.UUID;

import org.apache.commons.lang3.StringUtils;
import org.fenixedu.academic.domain.exceptions.DomainException;
import org.fenixedu.bennu.core.domain.Bennu;
import org.fenixedu.commons.i18n.LocalizedString;

import com.qubit.terra.framework.services.accessControl.Permission;
import com.qubit.terra.framework.services.accessControl.Profile;
import com.qubit.terra.framework.services.accessControl.ProfileBuilder;
import com.qubit.terra.framework.services.accessControl.ProfileBuilder.ObjectProviderStrategy;
import com.qubit.terra.qubAccessControl.domain.AccessControlProfile;

public class PersonIdentifierType extends PersonIdentifierType_Base {

    // Permission code from fenixedu-base
    public static final String PERSON_IDENTIFIER_ACCESS = "PERSON_IDENTIFIER_ACCESS";

    protected PersonIdentifierType() {
        super();
        setRootDomainObject(Bennu.getInstance());
    }

    public static PersonIdentifierType create(String code, LocalizedString name) {
        PersonIdentifierType type = new PersonIdentifierType();

        type.setCode(code);
        type.setName(name);
        type.initAccessControlProfiles();

        return type;
    }

    @Override
    public void setCode(String code) {
        Optional<PersonIdentifierType> findByCode = findByCode(code);
        if (findByCode.isPresent() && findByCode.get() != this) {
            throw new DomainException("error.person.personIdentifer.type.code");
        }

        super.setCode(code);
        getCreationAccessControlProfile().ifPresent(p -> {
            if (p instanceof AccessControlProfile) {
                ((AccessControlProfile) p).setCode(getIdentifierProfileCode());
            }
        });
    }

    @Override
    public void setName(LocalizedString name) {
        super.setName(name);
        getCreationAccessControlProfile().ifPresent(p -> {
            if (p instanceof AccessControlProfile) {
                ((AccessControlProfile) p).setName(new com.qubit.terra.framework.tools.primitives.LocalizedString());
            }
        });
    }

    public Optional<Profile> getCreationAccessControlProfile() {
        return Profile.findProfileByCode(getIdentifierProfileCode());
    }

    private void initAccessControlProfiles() {
        ProfileBuilder profileBuilder = Profile.builder().code(getIdentifierProfileCode())
                .permissions(Permission.findPermissionByCode(PERSON_IDENTIFIER_ACCESS).orElse(null))
                .name(new com.qubit.terra.framework.tools.primitives.LocalizedString()).autoGenerated(true)
                .provide(PersonIdentifierType.class, ObjectProviderStrategy.READ_ASSOCIATED);

        profileBuilder.build().addObject(this);
    }

    private String getIdentifierProfileCode() {
        return "PersonIdentifiersProfile_" + UUID.randomUUID().toString();
    }

    public static Optional<PersonIdentifierType> findByCode(String code) {
        return Bennu.getInstance().getPersonIdentifierTypesSet().stream().filter(type -> StringUtils.equals(type.getCode(), code))
                .findAny();
    }

    public void delete() {
        if (!getIdentifiersSet().isEmpty()) {
            throw new DomainException("error.person.personIdentifier.type.existingIdentifiers");
        }

        getCreationAccessControlProfile().ifPresent(p -> p.delete());

        setRootDomainObject(null);
        this.deleteDomainObject();
    }
}
